spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hamcam?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: elskvhfh12
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100
        jdbc.time_zone: Asia/Seoul
  mail:
    host: smtp.naver.com
    port: 465
    username: nskfn02@naver.com
    password: KLSS86T5WW3U
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  ai:
    openai:
      api-key: AIzaSyD6p4lqaa_hk1t830gowNIhKKJZDjy_bmo

livekit:
  ws-url: ws://192.168.0.2:7880
  api-key: devkey123
  api-secret: 78c9344275a8a63390768f35ccb864205edee5445cdb1e4b941878958d09e4b9e8475f678398e3d3927777bc82a8087c1d39db0d6497aa200c072ef4f8fac88b