name: Build with Gradle (LiveKit 포함)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # ✅ GitHub Secrets로 설정한 사용자명과 토큰 사용
      GPR_USER: ${{ secrets.GPR_USER }}
      GPR_KEY: ${{ secrets.GPR_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle build cache
        uses: gradle/gradle-build-action@v2

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build
